xử lí click trong recyclerview, 1 số chỗ chưa dùng databinding
hoang143/MockProjectV3 pull request #1
Opened 2023-05-15 12:36 UTC by hoang143

2023-05-17 02:38 UTC, iamhiutrun commented
@hoang143 Chuyển sang Databinding, các chỗ hardcode tạo file dimesion với kích thước, string resource với text. Handle error với Resource- các tôi chỉ trong comment

2023-05-17 02:38 UTC, iamhiutrun requested changes
@hoang143 Chuyển sang Databinding, các chỗ hardcode tạo file dimesion với kích thước, string resource với text. Handle error với Resource- các tôi chỉ trong comment

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/MainActivity.java
Như này cũng được, nhưng tôi nhớ là có cách không cần phải làm tay khởi tạo từng fragment và OnItemSelected như này: Navigation Component + BottomNavigation
https://blog.devgenius.io/bottom-navigation-made-simple-using-jetpack-navigation-component-efcdbfc913be

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/OnPopularListener.java
>      void onPopularClick(int position);
Nhớ format code trước khi tạo pull request. Chuyển sang tên có nghĩa như: onItemClickListener. void onItemClick...

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/OnUpcomingListener.java
> +public interface OnUpcomingListener {
Popular với Upcomming giống ViewHolder khum? Sao không dùng chung là onItemClickListener

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/PopularAdapter.java
Merge Popular + Upcomming thành 1 cái Adapter: MovieAdapter + MovieViewHolder

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/PopularAdapter.java
>              tvTitle = itemView.findViewById(R.id.tvTitle);
Đoạn này không sử dụng DataBinding được à?

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/UpComingAdapter.java
> +                .load("https://image.tmdb.org/t/p/w500/"
https://image.tmdb.org/t/p/w500/ ---> tạo constant

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/UpComingAdapter.java
> +
Movie movie = mMovies.get(position);

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/adapter/UpComingAdapter.java
> +            this.tvTitle = itemView.findViewById(R.id.tvTitle_Upcoming);
databinding

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
>      public static MovieRepository getInstance(){
Singleton. Good job

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
> +                        )
Handle exception như này:
```
class Resource{};
class Success<T>  extends Resource {
private String message,
private T data;
}
class Loading extends Resource{}
class Error extends Resource{
private String message;
}
```

Khi value của Livedata is Loading ---> Show Loading
is Error ---> hide loading ---> show error
is Success ---> hide loading ---> show data

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
> +    }
handle tương tự như trên

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
> +                    Credentials.API_KEY,
bỏ API_Key vào Interceptor:
https://stackoverflow.com/a/32606841

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
> +                    Credentials.API_KEY,
như trên

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/repositories/MovieRepository.java
> +                    Credentials.API_KEY,
như trên

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/HomeFragment.java
> +        searchView = view.findViewById(R.id.svHome);
format code, databinding

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/HomeFragment.java
>      }
xử lý status của response tại đây theo cách sử dụng Resource ở trên

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/HomeFragment.java
> +                }
giải thích đoạn này nha. Cơ chế load new page như này:
Ví dụ list của mình có 10 items. Khi user lướt đến item thứ i (tuỳ mình define) thì load new page.

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/HomeFragment.java
> +                }
tương tự load new page

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/LoginFragment.java
> +        etPassword = view.findViewById(R.id.etPasswordLogin);
databinding

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/MovieDetailFragment.java
> +        ivPoster = view.findViewById(R.id.ivPoster_MovieDetails);
databinding

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/ui/main/MovieDetailFragment.java
> +                    .load("https://image.tmdb.org/t/p/w500/"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/utils/MovieApi.java
>              @Query("api_key") String key,
Interceptor

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/utils/MovieApi.java
> +            @Query("api_key") String key,
Interceptor

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/java/com/example/mockprojectv3/utils/MovieApi.java
> +            @Query("api_key") String key,
Interceptor

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +        android:padding="20dp"
harcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:text="Welcome Mr.Sunday"
Hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:layout_marginVertical="5dp"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:textSize="19dp"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:layout_height="50dp"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            app:cardCornerRadius="20dp"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:textColorHint="#8E8E93"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_home.xml
> +            android:text="Search Movie..."
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_login.xml
> +        android:text="Hello There,\nWelcome Back"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_login.xml
> +        android:text="New User, Sign up?"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_login.xml
> +        android:textStyle="bold"
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_profile.xml
> +                android:text="Van Dinh Hoang" />
hardcode

2023-05-17 02:38 UTC, iamhiutrun commented on app/src/main/res/layout/fragment_signup.xml
> +        android:text="Welcome"
hardcode

2023-05-18 04:09 UTC, hoang143 commented on app/src/main/res/layout/fragment_signup.xml
> +        android:text="Welcome"
done

2023-06-04 08:04 UTC, merged